_Einführung in Python, Clemens Brunner, 10.5.2021_

# 9 &ndash; Numerische Daten

## Allgemeines
Python wurde ursprünglich als einfach zu erlerndende Lehr-Programmiersprache entwickelt. Aufgrund der Einfachheit und der Möglichkeit, Zusatzpakete sehr einfach nutzen zu können, hat sich Python auch im wissenschaftlichen Bereich (Datenanalyse, Machine Learning) als Quasi-Standard etabliert. [SciPy](http://www.scipy.org/) fasst mehrere wichtige Pakete zusammen, welche für die Datenanalyse essentiell sind:
* [NumPy](http://www.numpy.org/) (Arbeiten mit numerischen Daten)
* [SciPy (Bibliothek)](http://www.scipy.org/scipylib/index.html) (wichtige Algorithmen für diverse wissenschaftliche Anwendungen)
* [Matplotlib](http://matplotlib.org/) (Erstellen von Grafiken)
* [Pandas](http://pandas.pydata.org/) (Arbeiten mit Tabellen)
* [SymPy](http://www.sympy.org/en/index.html) (symbolisches Rechnen)
* [IPython](http://ipython.org/) (erweiterter interaktiver Python-Interpreter)

Darüber hinaus gibt es aber noch eine große Anzahl an weiteren exzellenten Paketen für speziellere Anwendungen wie z.B. [scikit-learn](http://scikit-learn.org/stable/) (Machine Learning), [statsmodels](http://www.statsmodels.org/stable/index.html) (Statistik), oder [scikit-image](http://scikit-image.org/) (Bildverarbeitung). Diese Pakete setzen meist zumindest NumPy als Grundlage voraus, welches wir in dieser Einheit kennenlernen werden.

## IPython
Der Python-Interpreter kann im Script-Modus oder im interaktiven Modus verwendet werden. Letzterer eignet sich zum interaktiven Verarbeiten von Daten (also z.B. auch zum Ausprobieren von Ideen mittels [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop)). Das Paket IPython fügt dem interaktiven Modus von Python einige zusätzliche Funktionen hinzu, die das Arbeiten komfortabler gestalten (z.B. farbliche Hervorhebung der Syntax, einfacher Zugriff auf bereits ausgeführte Befehle und Ergebnisse, hervorragende Vervollständigung von Befehlen mittels Tab-Completion, viele Zusatzfunktionen durch sogenannte Magic Functions). Deswegen sollte man eigentlich immer IPython und nicht den "nackten" Python-Interpreter für interaktive Aufgaben verwenden.

IPython stellt sowohl eine interaktive Konsole als auch ein Browser-basierendes Notebook (Jupyter) zur Verfügung. Wir beschäftigen uns hier aus Zeitgründen nur mit ersterem (angemerkt sei jedoch, dass dieses Dokument als Jupyter Notebook mit IPython erstellt wurde).

IPython kann im Terminal (mit dem Befehl `ipython`) oder als Qt-Console gestartet werden. Letzteres bietet u.a. zusätzlich die Möglichkeit, Grafiken direkt darzustellen. Auch Spyder oder PyCharm verwenden letztendlich IPython als interaktive Konsolen.

## NumPy
[NumPy](http://wiki.scipy.org/Tentative_NumPy_Tutorial) ist die Basis der allermeisten wissenschaftlichen Pakete in Python. Es stellt einen hocheffizienten Datentyp für numerische Daten zur Verfügung, nämlich ein homogenes multidimensionales (n-dimensionales) Array (auch kurz ND-Array bzw. `ndarray` genannt) &ndash; Listen wären dafür viel zu ineffizient, da sie unterschiedliche Elemente enthalten können. Homogen bedeutet, dass alle Elemente eines Arrays denselben Datentyp haben (z.B. lauter `float`-Zahlen) &ndash; dadurch können Berechnungen wesentlich effizienter und schneller ausgeführt werden. Multidimensional bedeutet, dass ein Array beliebig viele Dimensionen (Achsen) besitzen kann. Jedes Element wird daher mit einem Tupel indiziert, welches seine genaue Position innerhalb des Arrays beschreibt.

Das offizielle Tutorial [NumPy: the absolute basics for beginners](https://numpy.org/devdocs/user/absolute_beginners.html) ergänzt bzw. vertieft die Inhalte dieser Unterlagen &ndash; die Lektüre ist sehr zu empfehlen!

Beginnen wir aber mit einem Beispiel (Details zu den einzelnen Schritten folgen dann später). Der erste Schritt ist (wie bei jedem Paket bzw. Modul) das Importieren des Pakets NumPy. Konventionell importiert man es mit dem Kürzel `np`:

In [1]:
import numpy as np

Nun kann man alle NumPy-Funktionen mit Hilfe des Objekts `np` ansprechen. Wir erstellen nun eine Zahlensequenz aus 15 Zahlen:

In [2]:
a = np.arange(15)  # 15 Zahlen von 0 bis 14

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Der Typ des Objekts `a` ist nun keine Liste, sondern tatsächlich ein NumPy-Array, welches als `numpy.ndarray` bezeichnet wird:

In [4]:
type(a)

numpy.ndarray

NumPy-Arrays besitzen eine Form (Shape):

In [5]:
a.shape  # 15 Elemente in einer Dimension (Achse)

(15,)

Diese Form kann man auch verändern:

In [6]:
a = a.reshape(3, 5)  # umwandeln in 3 Zeilen und 5 Spalten

In [7]:
a  # 2 Dimensionen (Achsen), 1. Achse (=Zeilen) hat Länge 3, 2. Achse (=Spalten) hat Länge 5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.ndim  # Anzahl an Dimensionen (Achsen), auch Rank genannt

2

In [9]:
a.shape  # Länge der einzelnen Achsen

(3, 5)

Unabhängig von der Form kann man auch die Gesamtanzahl der Elemente im Array bestimmen:

In [10]:
a.size  # Anzahl aller Elemente im Array

15

NumPy-Arrays sind homogene Datentypen, d.h. alle Elemente im Array müssen denselben Typ haben. Diesen Typ kann man wie folgt bestimmen:

In [11]:
a.dtype  # Datentyp aller Elemente im Array

dtype('int64')

## Erstellen von Arrays
Arrays können mit der Funktion `np.array` aus Python-Listen erstellt werden. Im folgenden Beispiel übergeben wir der Funktion eine Liste als Argument, und daraus wird dann ein NumPy-Array erzeugt (zurückgegeben):

In [12]:
b = np.array([1.1, 3.14, 7.68, -12.69, -4.55])  # aus einer normalen Liste
b

array([  1.1 ,   3.14,   7.68, -12.69,  -4.55])

Eine Liste von Listen wird in ein 2D-Array (Tabelle, besteht aus Zeilen und Spalten) konvertiert:

In [13]:
c = np.array([[1, 2, 3], [4, 5, 6]])  # aus einer Liste von Listen
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c.shape  # 2 Zeilen, 3 Spalten

(2, 3)

Im Gegensatz zu Listen, welche dynamisch wachsen können, sollte die Größe von Arrays bereits bei der Erstellung bekannt sein, da das Hinzufügen von Zeilen oder Spalten relativ langsam ist. Hierfür gibt es einige praktische Konstruktionen, welche die Arrays mit Platzhalterelementen wie z.B. lauter Nullen erzeugen.

In [15]:
np.zeros((3, 4))  # Nullen - Achtung: die Funktion hat nur 1 Argument, nämlich das Tupel (3, 4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 4))  # Einsen

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Arrays die mit Zahlen ungleich 0 oder 1 gefüllt werden sollen, kann man mit der Funktion `np.full` erzeugen:

In [17]:
np.full((3, 4), 66)  # 3 Zeilen, 4 Spalten, alle Elemente gleich 66

array([[66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66]])

Analog zur Builtin-Funktion `range` können mit `np.arange` Arrays mit Folgen von Zahlen erstellt werden. Hier sind nicht nur ganze Zahlen möglich, sondern auch Kommazahlen. Auch hier zählt der letzte Wert (Stop-Wert) nicht mehr zum Bereich dazu.

In [18]:
np.arange(5, 17)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
np.arange(0.3, 5.4, 0.6)  # von 0.3 bis 5.4 mit Schrittweite 0.6

array([0.3, 0.9, 1.5, 2.1, 2.7, 3.3, 3.9, 4.5, 5.1])

Wenn man die Anzahl der Elemente (anstatt der Schrittweite) vorgeben will, verwendet man am besten die Funktion `linspace` (hier zählen sowohl Start- als auch Endwert zum Bereich):

In [20]:
np.linspace(1, 10, 10)  # 10 Elemente von 1 bis 10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(1, 10, 10, dtype=int)  # wie oben, nur Integer-Elemente

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.linspace(1, 10, 25)  # 25 Elemente von 1 bis 10

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

Sollen die Elemente nicht den gleichen (linearen) Abstand haben sondern logarithmisch unterteilt sein gibt es analog dazu die Funktion `logspace`:

In [23]:
np.logspace(0, 4, 8)  # 8 Werte von 10**0 bis 10**4

array([1.00000000e+00, 3.72759372e+00, 1.38949549e+01, 5.17947468e+01,
       1.93069773e+02, 7.19685673e+02, 2.68269580e+03, 1.00000000e+04])

## Rechnen mit Arrays
### Arithmetische Operationen
Arithmetische Operationen werden grundsätzlich elementweise angewendet.

In [24]:
a = np.arange(100, 700, 100).reshape((2, 3))
b = np.arange(1, 7).reshape((2, 3))

In [25]:
a

array([[100, 200, 300],
       [400, 500, 600]])

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a + b

array([[101, 202, 303],
       [404, 505, 606]])

In [28]:
a * b

array([[ 100,  400,  900],
       [1600, 2500, 3600]])

In [29]:
b**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [30]:
a < 300

array([[ True,  True, False],
       [False, False, False]])

Sind die zwei Arrays nicht gleich groß, wird das kleinere Array falls möglich vergrößert (d.h. Werte werden automatisch dupliziert) &ndash; dies nennt man *Broadcasting*. Das folgende Beispiel zeigt eine Multiplikation von einem Array der Shape (2, 3) mit der Zahl 5, was einer Shape von (1,) entspricht:

In [31]:
b.shape

(2, 3)

In [32]:
b * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

Hier wird also die Zahl 5 automatisch vervielfältigt, sodass die Operation elementweise durchgeführt werden kann. Im Prinzip ist diese Operation äquivalent zu folgender Schreibweise:

In [33]:
b * np.array([[5, 5, 5], [5, 5, 5]])

array([[ 5, 10, 15],
       [20, 25, 30]])

Ein weiteres Beispiel für Broadcasting ist, wenn wir ein Array `c` wie folgt erstellen: 

In [34]:
c = np.array([1, 2, 3])

Wir können nun das Array `c` direkt zum Array `b` addieren, weil die Dimensionen kompatibel sind: `b` hat 2 Zeilen und 3 Spalten und `c` hat 3 Elemente. Durch Broadcasting wird die Operation nun spaltenweise angewendet:

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
c

array([1, 2, 3])

In [37]:
b + c

array([[2, 4, 6],
       [5, 7, 9]])

### Methoden
Viele Funktionen wie z.B. `sum`, `mean`, `min` oder `max` sind als Methoden von `ndarray`-Objekten verfügbar. Standardmäßig verarbeiten sie dabei alle Elemente so, als ob diese in einer Dimension wären. Alternativ zu den Methoden gibt es aber auch Funktionen mit dem gleichen Namen.

In [38]:
a.mean()  # Methode

350.0

In [39]:
np.mean(a)  # Funktion

350.0

In [40]:
b.sum()

21

In [41]:
b.max()

6

In [42]:
a.min()

100

Man kann diese Funktionen/Methoden aber auch auf einzelne Dimensionen (auch "Achsen" genannt) anwenden, z.B. auf Zeilen oder Spalten. Dabei entspricht `0` den Zeilen und `1` den Spalten.

In [43]:
a.mean(axis=0)  # Mittelwert entlang der Zeilen, d.h. Spaltenmittelwerte

array([250., 350., 450.])

In [44]:
a.mean(axis=1)  # Mittelwert entlang der Spalten, d.h. Zeilenmittelwerte

array([200., 500.])

## Indizieren und Slicen
Analog zu anderen Sequenzdatentypen (z.B. String, Liste oder Tupel) können einzelne Elemente aus Arrays durch Indizieren bzw. Slicen herausgegriffen werden. Eindimensionale Arrays werden im Prinzip genau wie Listen indiziert.

In [45]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [46]:
a[0]  # erstes Element (wie in Python üblich beginnt auch hier die Indizierung bei 0)

0

In [47]:
a[-2]  # vorletztes Element

512

In [48]:
a[2:5]  # drei Elemente, beginnend mit Position 2

array([ 8, 27, 64])

In [49]:
a[::2]  # jedes zweite Element

array([  0,   8,  64, 216, 512])

Mehrdimensionale Arrays haben *einen Index pro Achse*.

In [50]:
b = np.random.randint(0, 100, (5, 4))

In [51]:
b

array([[14, 13, 98, 12],
       [26, 33, 15, 48],
       [ 5, 16, 15, 53],
       [28, 32, 90, 17],
       [50, 70, 12, 99]])

In [52]:
b.shape

(5, 4)

In [53]:
b[2, 3]  # 3. Zeile, 4. Spalte

53

In [54]:
b[:, -1]  # alle Zeilen, letzte Spalte

array([12, 48, 53, 17, 99])

In [55]:
b[0, :]  # erste Zeile

array([14, 13, 98, 12])

In [56]:
b[1:3, 2:]

array([[15, 48],
       [15, 53]])

Mit Listen kann man auch (mehrere) spezifische Positionen aus einem Array indizieren. Der Einfachkeit halber sei dies an einem 1D-Array veranschaulicht:

In [57]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [58]:
idx = [2, 7, 10, 10]  # wir wollen das 2., 7., 10. und 10. Element herausgreifen
idx

[2, 7, 10, 10]

In [59]:
a[idx]

array([  4,  49, 100, 100])

Den Namen für die Liste benötigt man nicht, man kann diese direkt innerhalb der eckigen Klammern angeben (das erste eckige Klammernpaar ist die Indizierung, und das zweite eckige Klammernpaar kennzeichnet die Liste):

In [60]:
a[[2, 7, 10, 10]]

array([  4,  49, 100, 100])

Mit Bool'schen Indexarrays kann man Arrays ebenfalls indizieren (maskieren):

In [61]:
a % 2 == 0  # wird elementweise berechnet, True bei geraden bzw. False bei ungeraden Zahlen

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [62]:
a[a % 2 == 0]

array([  0,   4,  16,  36,  64, 100])

Es werden hier also nur jene Elemente herausgegriffen, für die das Indexarray `True` ist.

## Form (Shape)
Die Form eines Arrays lässt sich auf folgende Arten einsehen bzw. ändern:

In [63]:
c = np.random.randint(-500, 500, (3, 4))
c

array([[-313,  332, -341, -171],
       [ 173, -341, -311, -451],
       [  29, -210,   97, -478]])

In [64]:
c.shape  # gibt die aktuelle Form aus

(3, 4)

In [65]:
c.shape = 2, 6  # ändert die Form in place
c

array([[-313,  332, -341, -171,  173, -341],
       [-311, -451,   29, -210,   97, -478]])

In [66]:
c.resize((4, 3))  # ändert die Form in place
c

array([[-313,  332, -341],
       [-171,  173, -341],
       [-311, -451,   29],
       [-210,   97, -478]])

In [67]:
c.reshape((1, -1))  # reshape ändert das Objekt nicht (-1 bedeutet, dass der Wert automatisch bestimmt wird)
c

array([[-313,  332, -341],
       [-171,  173, -341],
       [-311, -451,   29],
       [-210,   97, -478]])

In [68]:
c = c.reshape((1, -1))  # daher muss man einen Namen zuweisen, um damit weiterarbeiten zu können
c

array([[-313,  332, -341, -171,  173, -341, -311, -451,   29, -210,   97,
        -478]])

Der Unterschied zwischen `resize` und `reshape` ist also, das `resize` das Array direkt modifiziert und `reshape` lediglich ein neues geändertes Array zurückgibt.

## Kombinieren von Arrays
Mit den Funktionen `hstack` und `vstack` können Arrays horizontal bzw. vertikal miteinander kombiniert werden.

In [69]:
a = np.random.randint(-100, 100, (2, 3))
b = np.random.randint(-100, 100, (2, 3))

In [70]:
a

array([[ -2,   0,  93],
       [ 15, -18,  -5]])

In [71]:
b

array([[ 88, -20, -70],
       [  2,  72, -55]])

In [72]:
np.hstack((a, b))

array([[ -2,   0,  93,  88, -20, -70],
       [ 15, -18,  -5,   2,  72, -55]])

In [73]:
np.vstack((a, b))

array([[ -2,   0,  93],
       [ 15, -18,  -5],
       [ 88, -20, -70],
       [  2,  72, -55]])

Die Funktionen `column_stack` und `row_stack` liefern bei 2D-Arrays dieselben Ergebnisse wie `hstack` und `vstack`. Es gibt jedoch Unterschiede bei 1D-Arrays.

In [74]:
np.column_stack((a, b))

array([[ -2,   0,  93,  88, -20, -70],
       [ 15, -18,  -5,   2,  72, -55]])

In [75]:
np.row_stack((a, b))

array([[ -2,   0,  93],
       [ 15, -18,  -5],
       [ 88, -20, -70],
       [  2,  72, -55]])

In [76]:
c = np.random.randint(-100, 100, 5)
c

array([-69,  13, -39, -38, -44])

In [77]:
d = np.random.randint(-100, 100, 5)
d

array([ 64, -86,  32, -22,  19])

In [78]:
c.shape

(5,)

In [79]:
d.shape

(5,)

In [80]:
np.row_stack((c, d))

array([[-69,  13, -39, -38, -44],
       [ 64, -86,  32, -22,  19]])

In [81]:
np.column_stack((c, d))

array([[-69,  64],
       [ 13, -86],
       [-39,  32],
       [-38, -22],
       [-44,  19]])

In [82]:
np.hstack((c, d))

array([-69,  13, -39, -38, -44,  64, -86,  32, -22,  19])

In [83]:
np.vstack((c, d))

array([[-69,  13, -39, -38, -44],
       [ 64, -86,  32, -22,  19]])

## Übungen

### Übung 1
Erstellen Sie ein eindimensionales Array mit den Zahlen von 0 (inklusive) bis 10 (exklusive) in Schritten von 0.1. Weisen Sie diesem Array den Namen `t` zu. Wie viele Elemente hat das Array? Wie lautet die Form (Shape) des Arrays?

### Übung 2
Erstellen Sie aus dem Array `t` aus Übung 1 ein zweidimensionales Array `s`, welches die gleichen Elemente beinhaltet, jedoch aus 20 Zeilen (und der entsprechenden Anzahl an Spalten) besteht.

### Übung 3
Das Modul `np.random` enthält viele Funktionen zum Arbeiten mit Zufallszahlen. Erstellen Sie ein zweidimensionales Array `u` der Form (100, 8), welches aus zufälligen Ganzzahlen im Bereich \[-1000, 1000) besteht (d.h. -1000 ist dabei, 1000 nicht). Setzen Sie vorher den [Seed](https://de.wikipedia.org/wiki/Seed_key) (Startwert für die Initialisierung des Zufallszahlengenerators) mit dem Befehl `np.random.seed(4711)`. Berechnen Sie dann folgende Größen von `u`:

* Summe aller Elemente
* Mittelwert aller Elemente
* Zeilenmittelwerte
* Spaltenmittelwerte
* Maxima und Minima jeder Spalte
* Maxima und Minima jeder Zeile
* Maximum der Zeilenmittelwerte

*Hinweis:* Das Modul `np.random` ist komplett unabhängig vom Modul `random` (in der Python-Standardbibliothek). Immer wenn Sie mit NumPy-Arrays arbeiten und Zufallszahlen benötigen, sollten Sie `np.random` verwenden.

### Übung 4
Erstellen Sie ein dreidimensionales Array `x` der Form (3, 10, 5), welches die Zahlen von 1 bis 150 enthält. Wie lauten die *drei* Mittelwerte wenn Sie über die letzten beiden Dimensionen mitteln?

*Hinweis:* Der Mittelwert aller Elemente von `x[0, :, :]` ist der erste gesuchte Mittelwert, jener von `x[1, :, :]` der zweite, und jener von `x[2, :, :]` der dritte. Sie können so die drei Mittelwerte berechnen, oder kürzer wenn Sie das `axis`-Argument von `np.mean` auf ein Tupel setzen, welches die Achsen beschreibt, über die Sie mitteln möchten (also die Achsen 1 und 2, da Python bei 0 zu zählen beginnt).

### Übung 5
Erstellen Sie ein (8, 8)-Array `chess` mit einem Schachbrettmuster (verwenden Sie dafür die Werte 0 und 1). Es gibt viele mögliche Lösungen, gerne können Sie auch mehrere Varianten anführen. Sehen Sie sich z.B. die Hilfe zur Funktion `np.tile` an, oder erzeugen Sie zuerst ein Array aus lauter Nullen und fügen Sie dann an den entsprechenden Stellen Einsen ein (z.B. durch entsprechendes Indizieren oder mit `for`-Schleifen).

---
[![](cc_license.png)](http://creativecommons.org/licenses/by-nc-sa/4.0/)